import Foundation

/// Preprocessed per-surah statistics, bundled as `surah-stats.json` (generated by
/// `Scripts/generate_surah_stats.py` from the same Quran text the shipped pack was built from).
/// Everything here is precomputed at build time - the app never counts words or letters at runtime.
struct SurahStats: Decodable {
    /// Ayah count (Kufi/Hafs numbering).
    let ayahs: Int
    /// Arabic word count over the Uthmani text.
    let words: Int
    /// Base Arabic letters only - diacritics, harakat, and Quranic signs excluded.
    let letters: Int
    /// The juz numbers this surah spans, from the standard 30-juz table (e.g. [1, 2, 3]).
    let juz: [Int]
    /// Revelation type: "makkan" or "madinan".
    let type: String

    /// "Juz 1" / "Juz 1-3" - the coverage as the info sheet displays it.
    var juzLabel: String {
        guard let first = juz.first else { return "" }
        guard let last = juz.last, last != first else { return "Juz \(first)" }
        return "Juz \(first)-\(last)"
    }

    /// "Makkan" / "Madinan", capitalized for display.
    var revelationLabel: String {
        type == "makkan" ? "Makkan" : "Madinan"
    }
}

enum SurahStatsStore {
    /// All 114 surahs' stats, decoded from the bundled JSON exactly once. ~8 KB resident.
    static let all: [Int: SurahStats] = {
        // Xcode copies the file-reference resource flat into the bundle root; check the
        // grouped subdirectories too, mirroring how the .qpk packs are located.
        let url = Bundle.main.url(forResource: "surah-stats", withExtension: "json", subdirectory: "Quran")
            ?? Bundle.main.url(forResource: "surah-stats", withExtension: "json", subdirectory: "Data/Quran")
            ?? Bundle.main.url(forResource: "surah-stats", withExtension: "json")
        guard let url,
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode([String: SurahStats].self, from: data) else {
            return [:]
        }
        var byNumber: [Int: SurahStats] = [:]
        byNumber.reserveCapacity(decoded.count)
        for (key, value) in decoded {
            if let number = Int(key) { byNumber[number] = value }
        }
        return byNumber
    }()

    static func stats(for surahNumber: Int) -> SurahStats? {
        all[surahNumber]
    }
}
